### ISSUE TITLE
Response Failed /api/json

### ISSUE THREAD

**Issue by fahmiirsyadk** [Javanixus/octolist#2]
#### ![ for helping guidelines ](https://github.com/Javanixus/octolist/blob/master/CONTRIBUTING.md)
<b>#bug</b> 

co tulung gawekno page ng api gawe nyoba request login. @zharpi @Javanixus/backend 
iki code ku 

`  methods: {
    auth() {
      this.$http.get('http://localhost:8000/api/json')
      .then(response => {
        console.log(response)
      })
    }
  }`

**Comment by piharpi** [comment]
sek mageh mahami

**Comment by fahmiirsyadk** [comment]
![deepinscreenshot_20171215071939](https://user-images.githubusercontent.com/17546686/34020867-2f4e2fd8-e169-11e7-8368-2ce74c874ed5.png)

**#bug** fixed

on commit ![this commit](https://github.com/Javanixus/octolist/commit/06ede598c74dc640f0d4364edc220787233aade4)
