### ISSUE TITLE
routes not showing up

### ISSUE THREAD

**Issue by fahmiirsyadk** [Javanixus/octolist#3]
ga muncul ng misal access page admin 
**#bug**

> localhost:8000/admin

not found dadine , koyok e kudu gawe page siji siji ?

**Comment by piharpi** [comment]
sek mageh bingung

**Comment by piharpi** [comment]
kurang paham @blubMe  jelasno maneh

**Comment by fahmiirsyadk** [comment]
fixed yay :tada: ![**click this commit**](https://github.com/Javanixus/octolist/commit/e1b24c7ab674e9113afd356abdfc9fab2a33f6a2)
